# Site
repository: sproogen/resume-theme

# Content config version
version: 2

# Personal info
name: Cynthia
title: Hobbyist

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
